# Generated by Django 4.1.3 on 2022-11-21 15:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_itemsmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsmodel',
            name='price',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='itemsmodel',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
