# Generated by Django 4.1.3 on 2022-11-25 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_itemsmodel_price_alter_itemsmodel_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemsmodel',
            name='image',
            field=models.ImageField(upload_to='media/image'),
        ),
    ]
